version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: "10k"
        max-file: "5"