version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store: