version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    networks:
    - rps-network
  web:
    container_name: reservation_pc_seat
    build:
      context: .
      dockerfile: docker/next/Dockerfile
    volumes:
      - next-node-modules:/node_modules
    networks:
      - rps-network
    ports:
      - "4000:3000"
    tty: true
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db?schema=postgres
    # command: >
    #   sh -c "npm run start"
networks:
  rps-network:

volumes:
  next-node-modules: