export default function Head() {
  return (
    <>
      <title>LC PC席予約</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        property="og:description"
        content="Learning Commons PC席の予約サイトです"
      />
      <meta
        property="og:image"
        content="https://reservation-pc-seat.vercel.app/ogp.png"
      />
    </>
  );
}
